// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoqwqenazffjdddqjuhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcXdxZW5hemZmamRkZHFqdWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjMxMDIsImV4cCI6MjA2MjEzOTEwMn0.Kdawr_q7wqsroEWfwOB5zdHbRU_7pL1VIhYnaXOBg18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);